[project]
authors = ["Seif Lotfy <seif.lotfy@gmail.com>"]
channels = ["https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "mojo-bloomfilter"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=25.5.0,<26"
mojo = ">=25.5.0,<26"
